#!/usr/bin/env python
import os
import sys

env = SConscript("../extern/godot-cpp/SConstruct")

# For the reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

env.Append(CPPPATH=['../extern/sockpp/include/'])
# env.Append(RPATH=[Literal("\$$ORIGIN:.")])

sources = Glob("*.cpp")
sources.append('../extern/sockpp/src/acceptor.cpp')
sources.append('../extern/sockpp/src/connector.cpp')
sources.append('../extern/sockpp/src/datagram_socket.cpp')
sources.append('../extern/sockpp/src/exception.cpp')
sources.append('../extern/sockpp/src/inet_address.cpp')
sources.append('../extern/sockpp/src/inet6_address.cpp')
sources.append('../extern/sockpp/src/result.cpp')
sources.append('../extern/sockpp/src/socket.cpp')
sources.append('../extern/sockpp/src/stream_socket.cpp')

sources.append('../extern/sockpp/src/unix/unix_address.cpp')


output_name = "../frontend/bin/libmesha{}{}".format(env["suffix"], env["SHLIBSUFFIX"])

if env["platform"] == "macos":
    output_name = "../frontend/bin/libmesha.{}.{}.framework/libmesha.{}.{}".format(env["platform"],
                                                                                   env["target"],
                                                                                   env["platform"],
                                                                                   env["target"])

extension_library = env.SharedLibrary(output_name, source=sources)

env.Alias('gdextension', extension_library)
env.Alias('extension', extension_library)
env.Alias('cpp', extension_library)

