#!/usr/bin/env python
import os
import sys

env = SConscript("../extern/godot-cpp/SConstruct")

# For the reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

env.Append(CXXFLAGS=["-Wno-deprecated-builtins"])
env.Append(CPPPATH=['../build/include'])
env.Append(LIBPATH=['../build/lib', '../build', '../frontend/bin'])
env.Append(LIBS=['ecl', 'mesha-core'])
env.Append(RPATH=[Literal("\$$ORIGIN:.")])

# env.Append(CPPPATH=['./'])
sources = Glob("*.cpp")

output_name = "../frontend/bin/libmesha{}{}".format(env["suffix"], env["SHLIBSUFFIX"])

if env["platform"] == "macos":
    output_name = "../frontend/bin/libmesha.{}.{}.framework/libmesha.{}.{}".format(env["platform"],
                                                                                   env["target"],
                                                                                   env["platform"],
                                                                                   env["target"])

extension_library = env.SharedLibrary(output_name, source=sources)

env.Alias('gdextension', extension_library)
env.Alias('extension', extension_library)
env.Alias('cpp', extension_library)

