(in-package #:mesha)

(defclass application ()
  ((document :initform nil)
   (viewport :initarg :viewport)
   (messages :initform (queues:make-queue :simple-queue))
   (context :initarg :context)
   (commands :initform (queues:make-queue :simple-cqueue))
   (fonts :initform (make-hash-table))))

(defun get-viewport (app)
  (slot-value app 'viewport))

(defun application-run (app init-fn update-fn render-fn)
  (v:info :application "Starting application loop")
  (let ((view (get-viewport app)))
    (sdl2:with-init (:everything)
      (let ((ctx (mesha-native:create-context)))
        (assert ctx)
        (setf (slot-value app 'context) ctx))
      (funcall init-fn app)
      (sdl2:with-window (win :title "Mesha" :flags '(:shown) :w (round (vx view)) :h (round (vy view)))
        (sdl2:with-renderer (renderer win :flags '(:accelerated :presentvsync))
          (sdl2:with-event-loop (:method :poll)
            (:idle
             ()
             (sdl2:set-render-draw-color renderer 0 0 0 255)
             (sdl2:render-clear renderer)
             (funcall update-fn app)
             (funcall render-fn app renderer)
             (sdl2:render-present renderer))
            (:quit
             ()
             ()
             (v:info :application "Exiting event loop")
             t)))))))

